import banner
import time
from colorama import Fore
F_name = input("> First Name: ")
L_name = input("> Last Name: ")
Nickname = input("> Nickname: ")
Birthday = input("> Birthday (DDMMYYYY): ")
Bro = input("> Brother Name:")
sis = input("> sister Name:")
print("\n")
P_name = input("> Partners) Name: ")
P_lname = input("> Partners) Last Name: ")
P_birthday = input("> Partners) Birthday (DDMMYYYY): ")
print("\n")
Ch_name = input("> Child's name: ")
Ch_nickname = input("> Child's Nick Name: ")
Ch_Birthday = input("> Child's Birthday (DDMMYYYY): ")
print("\n")
pets_name = input("> Pets Name: ")
company_name = input("> Company Name: ")
print("\n")

list_ = [F_name, L_name, Bro, sis, Nickname, Birthday, P_name, P_lname,
         P_birthday, Ch_name, Ch_nickname, Ch_Birthday, pets_name, company_name]

keyWords = input(
    "> Do you want to add some key words about the victim? Y/[N]: ")
if keyWords == 'Y' or keyWords == 'y':
    keyWords2 = input("Enter your key words (hacker,gym,caty) : ")
    keyWords3 = keyWords2.split(",")

sp_chars = input(
    "> Do you want to add special chars at the end of words? ,'For example @ # $ % ^ & * ( ) _ + - =' Y/[N]: ")


t_bi_2av = Birthday[0:2]
t_bi_2av2 = Birthday[2:4]
t_bi_4av = Birthday[0:4]
t_bi_2ak = Birthday[6:8]
# --------------------------------
p_bi_2av = P_birthday[0:2]
p_bi_2av2 = P_birthday[2:4]
p_bi_4av = P_birthday[0:4]
p_bi_2ak = P_birthday[6:8]
# --------------------------------
ch_bi_2av = Ch_Birthday[0:2]
ch_bi_2av2 = Ch_Birthday[2:4]
ch_bi_4av = Ch_Birthday[0:4]
ch_bi_2ak = Ch_Birthday[6:8]



f = open(F_name+'.txt', 'a')

if keyWords == 'Y' or keyWords == 'y':
    for i in keyWords3:

        f.write(i+'\n')
        f.write(i+F_name+'\n')
        f.write(i+L_name+'\n')
        f.write(i+L_name+'\n')
        f.write(i+P_name+'\n')
        f.write(i+P_lname+'\n')
        f.write(i+Ch_name+'\n')
        f.write(i+Ch_nickname+'\n')
        # ------------------------------
        f.write(i+t_bi_2av+"\n")
        f.write(i+t_bi_2av2+"\n")
        f.write(i+t_bi_4av+"\n")
        f.write(i+t_bi_2ak+"\n")

        f.write(i+p_bi_2av+"\n")
        f.write(i+p_bi_2av2+"\n")
        f.write(i+p_bi_4av+"\n")
        f.write(i+p_bi_2ak+"\n")

        f.write(i+ch_bi_2av+"\n")
        f.write(i+ch_bi_2av2+"\n")
        f.write(i+ch_bi_4av+"\n")
        f.write(i+ch_bi_2ak+"\n")
        # ------------------------------
        f.write(i+'#'+'\n')
        f.write('#'+i+'\n')
        f.write(i+'$'+'\n')
        f.write('$'+i+'\n')
        f.write(i+'%'+'\n')
        f.write('%'+i+'\n')
        f.write(i+'##'+'\n')
        f.write('##'+i+'\n')
        f.write('$$'+i+'\n')

        f.write(i+t_bi_2av+'#'+'\n')
        f.write(i+t_bi_2av+'##'+'\n')
        f.write(i+t_bi_2av+'$'+'\n')
        f.write(i+t_bi_2av+'$$'+'\n')

        f.write(i+'1'+'#'+'\n')
        f.write(i+'2'+'#'+'\n')
        f.write(i+'3'+'#'+'\n')
        f.write(i+'4'+'#'+'\n')
        f.write(i+'5'+'#'+'\n')
        f.write(i+'6'+'#'+'\n')
        f.write(i+'7'+'#'+'\n')
        f.write(i+'8'+'#'+'\n')
        f.write(i+'9'+'#'+'\n')
        f.write(i+'12'+'#'+'\n')
        f.write(i+'23'+'#'+'\n')
        f.write(i+'45'+'#'+'\n')
        f.write(i+'56'+'#'+'\n')
        f.write(i+'67'+'#'+'\n')
        f.write(i+'78'+'#'+'\n')
        f.write(i+'89'+'#'+'\n')
        f.write(i+'90'+'#'+'\n')

        f.write(i+t_bi_2av+'1'+'#'+'\n')
        f.write(i+t_bi_2av+'2'+'#'+'\n')
        f.write(i+t_bi_2av+'3'+'#'+'\n')
        f.write(i+t_bi_2av+'4'+'#'+'\n')
        f.write(i+t_bi_2av+'5'+'#'+'\n')
        f.write(i+t_bi_2av+'6'+'#'+'\n')
        f.write(i+t_bi_2av+'7'+'#'+'\n')
        f.write(i+t_bi_2av+'8'+'#'+'\n')
        f.write(i+t_bi_2av+'9'+'#'+'\n')
        f.write(i+t_bi_2av+'12'+'#'+'\n')
        f.write(i+t_bi_2av+'23'+'#'+'\n')
        f.write(i+t_bi_2av+'45'+'#'+'\n')
        f.write(i+t_bi_2av+'56'+'#'+'\n')
        f.write(i+t_bi_2av+'67'+'#'+'\n')
        f.write(i+t_bi_2av+'78'+'#'+'\n')
        f.write(i+t_bi_2av+'89'+'#'+'\n')
        f.write(i+t_bi_2av+'90'+'#'+'\n')
        f.write(i+t_bi_2av+'##'+'\n')
        f.write(i+t_bi_2av+'$'+'\n')
        f.write(i+t_bi_2av+'$$'+'\n')

        f.write(i+t_bi_2av2+'#'+'\n')
        f.write(i+t_bi_2av2+'##'+'\n')
        f.write(i+t_bi_2av2+'$'+'\n')
        f.write(i+t_bi_2av2+'$$'+'\n')

        f.write(i+t_bi_2av2+'1'+'#'+'\n')
        f.write(i+t_bi_2av2+'2'+'#'+'\n')
        f.write(i+t_bi_2av2+'3'+'#'+'\n')
        f.write(i+t_bi_2av2+'4'+'#'+'\n')
        f.write(i+t_bi_2av2+'5'+'#'+'\n')
        f.write(i+t_bi_2av2+'6'+'#'+'\n')
        f.write(i+t_bi_2av2+'7'+'#'+'\n')
        f.write(i+t_bi_2av2+'8'+'#'+'\n')
        f.write(i+t_bi_2av2+'9'+'#'+'\n')
        f.write(i+t_bi_2av2+'12'+'#'+'\n')
        f.write(i+t_bi_2av2+'23'+'#'+'\n')
        f.write(i+t_bi_2av2+'45'+'#'+'\n')
        f.write(i+t_bi_2av2+'56'+'#'+'\n')
        f.write(i+t_bi_2av2+'67'+'#'+'\n')
        f.write(i+t_bi_2av2+'78'+'#'+'\n')
        f.write(i+t_bi_2av2+'89'+'#'+'\n')
        f.write(i+t_bi_2av2+'90'+'#'+'\n')
        f.write(i+t_bi_2av2+'##'+'\n')
        f.write(i+t_bi_2av2+'$'+'\n')
        f.write(i+t_bi_2av2+'$$'+'\n')

        f.write(i+t_bi_4av+'#'+'\n')
        f.write(i+t_bi_4av+'##'+'\n')
        f.write(i+t_bi_4av+'$'+'\n')
        f.write(i+t_bi_4av+'$'+'\n')


for i in list_:
    f.write(i+t_bi_2av+"\n")
    f.write(i+t_bi_2av2+"\n")
    f.write(i+t_bi_4av+"\n")
    f.write(i+t_bi_2ak+"\n")

    f.write(i+p_bi_2av+"\n")
    f.write(i+p_bi_2av2+"\n")
    f.write(i+p_bi_4av+"\n")
    f.write(i+p_bi_2ak+"\n")

    f.write(i+ch_bi_2av+"\n")
    f.write(i+ch_bi_2av2+"\n")
    f.write(i+ch_bi_4av+"\n")
    f.write(i+ch_bi_2ak+"\n")


if sp_chars == "Y" or sp_chars == 'y':
    for i in list_:
        f.write(i+'#'+'\n')
        f.write('#'+i+'\n')
        f.write(i+'$'+'\n')
        f.write('$'+i+'\n')
        f.write(i+'%'+'\n')
        f.write('%'+i+'\n')
        f.write(i+'##'+'\n')
        f.write('##'+i+'\n')
        f.write('$$'+i+'\n')

        f.write(i+t_bi_2av+'#'+'\n')
        f.write(i+t_bi_2av+'##'+'\n')
        f.write(i+t_bi_2av+'$'+'\n')
        f.write(i+t_bi_2av+'$$'+'\n')

        f.write(i+'1'+'#'+'\n')
        f.write(i+'2'+'#'+'\n')
        f.write(i+'3'+'#'+'\n')
        f.write(i+'4'+'#'+'\n')
        f.write(i+'5'+'#'+'\n')
        f.write(i+'6'+'#'+'\n')
        f.write(i+'7'+'#'+'\n')
        f.write(i+'8'+'#'+'\n')
        f.write(i+'9'+'#'+'\n')
        f.write(i+'12'+'#'+'\n')
        f.write(i+'23'+'#'+'\n')
        f.write(i+'45'+'#'+'\n')
        f.write(i+'56'+'#'+'\n')
        f.write(i+'67'+'#'+'\n')
        f.write(i+'78'+'#'+'\n')
        f.write(i+'89'+'#'+'\n')
        f.write(i+'90'+'#'+'\n')

        f.write(i+t_bi_2av+'1'+'#'+'\n')
        f.write(i+t_bi_2av+'2'+'#'+'\n')
        f.write(i+t_bi_2av+'3'+'#'+'\n')
        f.write(i+t_bi_2av+'4'+'#'+'\n')
        f.write(i+t_bi_2av+'5'+'#'+'\n')
        f.write(i+t_bi_2av+'6'+'#'+'\n')
        f.write(i+t_bi_2av+'7'+'#'+'\n')
        f.write(i+t_bi_2av+'8'+'#'+'\n')
        f.write(i+t_bi_2av+'9'+'#'+'\n')
        f.write(i+t_bi_2av+'12'+'#'+'\n')
        f.write(i+t_bi_2av+'23'+'#'+'\n')
        f.write(i+t_bi_2av+'45'+'#'+'\n')
        f.write(i+t_bi_2av+'56'+'#'+'\n')
        f.write(i+t_bi_2av+'67'+'#'+'\n')
        f.write(i+t_bi_2av+'78'+'#'+'\n')
        f.write(i+t_bi_2av+'89'+'#'+'\n')
        f.write(i+t_bi_2av+'90'+'#'+'\n')
        f.write(i+t_bi_2av+'##'+'\n')
        f.write(i+t_bi_2av+'$'+'\n')
        f.write(i+t_bi_2av+'$$'+'\n')

        f.write(i+t_bi_2av2+'#'+'\n')
        f.write(i+t_bi_2av2+'##'+'\n')
        f.write(i+t_bi_2av2+'$'+'\n')
        f.write(i+t_bi_2av2+'$$'+'\n')

        f.write(i+t_bi_2av2+'1'+'#'+'\n')
        f.write(i+t_bi_2av2+'2'+'#'+'\n')
        f.write(i+t_bi_2av2+'3'+'#'+'\n')
        f.write(i+t_bi_2av2+'4'+'#'+'\n')
        f.write(i+t_bi_2av2+'5'+'#'+'\n')
        f.write(i+t_bi_2av2+'6'+'#'+'\n')
        f.write(i+t_bi_2av2+'7'+'#'+'\n')
        f.write(i+t_bi_2av2+'8'+'#'+'\n')
        f.write(i+t_bi_2av2+'9'+'#'+'\n')
        f.write(i+t_bi_2av2+'12'+'#'+'\n')
        f.write(i+t_bi_2av2+'23'+'#'+'\n')
        f.write(i+t_bi_2av2+'45'+'#'+'\n')
        f.write(i+t_bi_2av2+'56'+'#'+'\n')
        f.write(i+t_bi_2av2+'67'+'#'+'\n')
        f.write(i+t_bi_2av2+'78'+'#'+'\n')
        f.write(i+t_bi_2av2+'89'+'#'+'\n')
        f.write(i+t_bi_2av2+'90'+'#'+'\n')
        f.write(i+t_bi_2av2+'##'+'\n')
        f.write(i+t_bi_2av2+'$'+'\n')
        f.write(i+t_bi_2av2+'$$'+'\n')

        f.write(i+t_bi_4av+'#'+'\n')
        f.write(i+t_bi_4av+'##'+'\n')
        f.write(i+t_bi_4av+'$'+'\n')
        f.write(i+t_bi_4av+'$'+'\n')


for i in list_:
    f.write(i+"\n")
    f.write(i+F_name+"\n")
    f.write(i+L_name+"\n")
    f.write(i+P_name+"\n")
    f.write(i+P_lname+"\n")
    f.write(i+Ch_name+"\n")
    f.write(i+Ch_nickname+"\n")
    f.write(i+pets_name+"\n")
    f.write(i+company_name+"\n")

    # ----------------------------------
    f.write(i+'1'+'\n')
    f.write(i+'2'+'\n')
    f.write(i+'3'+'\n')
    f.write(i+'4'+'\n')
    f.write(i+'5'+'\n')
    f.write(i+'6'+'\n')
    f.write(i+'7'+'\n')
    f.write(i+'8'+'\n')
    f.write(i+'9'+'\n')
    f.write(i+'12'+'\n')
    f.write(i+'23'+'\n')
    f.write(i+'45'+'\n')
    f.write(i+'56'+'\n')
    f.write(i+'67'+'\n')
    f.write(i+'78'+'\n')
    f.write(i+'89'+'\n')
    f.write(i+'90'+'\n')
    # ----------------------------------

    f.write(i+'.'+F_name+"\n")
    f.write(i+'.'+L_name+"\n")
    f.write(i+'.'+P_name+"\n")
    f.write(i+'.'+P_lname+"\n")
    f.write(i+'.'+Ch_name+"\n")
    f.write(i+'.'+Ch_nickname+"\n")
    f.write(i+'.'+pets_name+"\n")
    f.write(i+'.'+company_name+"\n")

    # ----------------------------------

    f.write(i+'-'+F_name+"\n")
    f.write(i+'-'+L_name+"\n")
    f.write(i+'-'+P_name+"\n")
    f.write(i+'-'+P_lname+"\n")
    f.write(i+'-'+Ch_name+"\n")
    f.write(i+'-'+Ch_nickname+"\n")
    f.write(i+'-'+pets_name+"\n")
    f.write(i+'-'+company_name+"\n")

    # ----------------------------------
    f.write(i+'_'+F_name+"\n")
    f.write(i+'_'+L_name+"\n")
    f.write(i+'_'+P_name+"\n")
    f.write(i+'_'+P_lname+"\n")
    f.write(i+'_'+Ch_name+"\n")
    f.write(i+'_'+Ch_nickname+"\n")
    f.write(i+'_'+pets_name+"\n")
    f.write(i+'_'+company_name+"\n")

    # -----------------------------

    f.write(F_name+'.'+i+"\n")
    f.write(L_name+'.'+i+"\n")
    f.write(P_name+'.'+i+"\n")
    f.write(P_lname+'.'+i+"\n")
    f.write(Ch_name+'.'+i+"\n")
    f.write(Ch_nickname+'.'+i+"\n")
    f.write(pets_name+'.'+i+"\n")
    f.write(company_name+'.'+i+"\n")

    # -----------------------------

    f.write(F_name+'-'+i+"\n")
    f.write(L_name+'-'+i+"\n")
    f.write(P_name+'-'+i+"\n")
    f.write(P_lname+'-'+i+"\n")
    f.write(Ch_name+'-'+i+"\n")
    f.write(Ch_nickname+'-'+i+"\n")
    f.write(pets_name+'-'+i+"\n")
    f.write(company_name+'-'+i+"\n")

    # -----------------------------

    f.write(F_name+'_'+i+"\n")
    f.write(L_name+'_'+i+"\n")
    f.write(P_name+'_'+i+"\n")
    f.write(P_lname+'_'+i+"\n")
    f.write(Ch_name+'_'+i+"\n")
    f.write(Ch_nickname+'_'+i+"\n")
    f.write(pets_name+'_'+i+"\n")
    f.write(company_name+'_'+i+"\n")

    # -----------------------------

    f.write(F_name+i+"\n")
    f.write(L_name+i+"\n")
    f.write(P_name+i+"\n")
    f.write(P_lname+i+"\n")
    f.write(Ch_name+i+"\n")
    f.write(Ch_nickname+i+"\n")
    f.write(pets_name+i+"\n")
    f.write(company_name+i+"\n")

print(Fore.RED+"=                                          1%|")
time.sleep(0.1)
print(Fore.RED+"==                                         3%|")
time.sleep(0.1)
print(Fore.RED+"===                                        6%|")
time.sleep(0.1)
print(Fore.RED+"====                                       8%|")
time.sleep(0.1)
print(Fore.RED+"=====                                      12%|")
time.sleep(0.1)
print(Fore.RED+"======                                     16%|")
time.sleep(0.1)
print(Fore.RED+"=======                                    18%|")
time.sleep(0.1)
print(Fore.YELLOW+"========                                   19%|")
time.sleep(0.1)
print(Fore.YELLOW+"=========                                  21%|")
time.sleep(0.1)
print(Fore.YELLOW+"==========                                 23%|")
time.sleep(0.1)
print(Fore.YELLOW+"===========                                26%|")
time.sleep(0.1)
print(Fore.YELLOW+"============                               28%|")
time.sleep(0.1)
print(Fore.YELLOW+"=============                              31%|")
time.sleep(0.1)
print(Fore.YELLOW+"==============                             32%|")
time.sleep(0.1)
print(Fore.YELLOW+"===============                            33%|")
time.sleep(0.1)
print(Fore.YELLOW+"================                           34%|")
time.sleep(0.1)
print(Fore.YELLOW+"=================                          35%|")
time.sleep(0.1)
print(Fore.YELLOW+"==================                         37%|")
time.sleep(0.1)
print(Fore.YELLOW+"===================                        42%|")
time.sleep(0.1)
print(Fore.YELLOW+"====================                       43%|")
time.sleep(0.1)
print(Fore.YELLOW+"=====================                      45%|")
time.sleep(0.1)
print(Fore.YELLOW+"======================                     46%|")
time.sleep(0.1)
print(Fore.BLUE+"=======================                    49%|")
time.sleep(0.1)
print(Fore.BLUE+"========================                   50%|")
time.sleep(0.1)
print(Fore.BLUE+"=========================                  52%|")
time.sleep(0.1)
print(Fore.BLUE+"==========================                 53%|")
time.sleep(0.1)
print(Fore.BLUE+"===========================                59%|")
time.sleep(0.1)
print(Fore.BLUE+"============================               61%|")
time.sleep(0.1)
print(Fore.BLUE+"=============================              64%|")
time.sleep(0.1)
print(Fore.BLUE+"==============================             65%|")
time.sleep(0.1)
print(Fore.BLUE+"===============================            68%|")
time.sleep(0.1)
print(Fore.BLUE+"================================           69%|")
time.sleep(0.1)
print(Fore.BLUE+"=================================          70%|")
time.sleep(0.1)
print(Fore.BLUE+"==================================         71%|")
time.sleep(0.1)
print(Fore.BLUE+"===================================        75%|")
time.sleep(0.1)
print(Fore.BLUE+"====================================       80%|")
time.sleep(0.1)
print(Fore.BLUE+"=====================================      86%|")
time.sleep(0.2)
print(Fore.GREEN+"======================================     89%|")
time.sleep(0.2)
print(Fore.GREEN+"=======================================    90%|")
time.sleep(0.2)
print(Fore.GREEN+"========================================   92%|")
time.sleep(0.2)
print(Fore.GREEN+"=========================================  95%|")
time.sleep(0.2)
print(Fore.GREEN+"========================================== 99%|")
time.sleep(0.3)
print(Fore.GREEN+"===========================================100%|")

print(Fore.RED+"> File "+F_name+" Created successfuly")

input("> (: Press Enter For Exit :)")